### ISSUE TITLE
Changes to repo organization

### ISSUE THREAD

**Issue by AliciaMstt** [bc-anaisabel/juniperus_paper#9]
- [x] Move your files explaining the steps done manually (not scripts) to `bin` instead of `data`
- [x] Explain in your README that not all your steps were done with scripts, but some manually 
- [x] It would be useful to add a diagram explaining the main steps of your pipeline 
- [x] Currently your general README and your scripts README numeration is confusing. Make sure to separate your steps and to make clear what is the name of your scritps and what isn't.

**Comment by bc-anaisabel** [comment]
Not sure I'll be adding the diagram at this point but the rest was done. All manual steps are now in numbered order in `/bin`
